repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        entry: cargo check --workspace
        language: system
        pass_filenames: false
